apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: kserve
    name: in-cluster  
      #server: 'https://kubernetes.default.svc'
  source:
    path: charts/kserve-resources
    repoURL: https://github.com/enaalsharairi/deploykf
    targetRevision: HEAD
      #chart: kserve-resources
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
