apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: example-private-helm-oci
  namespace: argocd
stringData:
  url: ghcr.io/enaalsharairi/deploykf
  name: deploykf-kserve
  type: helm
  enableOCI: "true"
  username: enaalsharairi
  password: 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
